branches:
  only: master
  except: master
  publish: True
releases: True
domains:
- schema:
    url: https://github.com/hugdru/schemas/blob/master/big_data-schema.yaml
  data:
    Scalability:
      Scalable Distribution Architecture: [horizontal partitioning of database, horizontal partitioning and replication]
      Scaling Out - Adding Data Storage Capacity: automatic data rebalancing
      Request Load Balancing: fixed connections to a request coordinator
      Granularity of Write Locks: locks on updated objects only
      Scalable Request Processing Architecture: centralized coordinator, but can be replicated
    Consistency:
      Object Level Atomic Updates: supported
      ACID Transactions: lightweight transactions
      Distributed Transactions: not supported
      Durable Writes: supported
      Quorum Reads and Writes: not supported
      Number of Replicas to Read: not supported
      Number of Replicas to Write: not supported
      Writes with Unavailable Replicas: a rollback at all replicas
      Read from Master Only: specified in the database configuration
      Resolving Write Conflicts: supported
    Query Language:
      API-based: supported
      Declarative Query Language: not suppported
      REST/HTTP-based Queries: supported
      Languages Supported: [Java, Python, C/C++, PHP, Ruby]
      Cursor-based Queries: not suppported
      JOIN-style queries: not suppported
      Complex Data Types: none
      Restrict Query Result Set Size: supported
      Key Matching Options: [exact, partial match, regular expressions]
      Sort Options: ascending
      Triggers: not supported
      Data Object Expiry: is supported
    Data Model:
      Data model: Column
      Fixed Schema: not required
      Opaque Data Objects: not required
      Hierarchical Data Objects: not supported
      Automatically allocated Primary Key: not supported
      Composite Keys: supported
      Secondary Indexes: not supported
      Query by Key Ranges: supported
      Query by Partial Keys: supported
      Query by Non-key Values: supported
      Map Reduce API: builtin
      Indexed Text Search: support in a plug-in
    Data Replication:
      Replication Architecture: master-slave
      Replication for Backup: supported
      Replication across Data Centers: supported by data center aware features
      Replica Writes: to master replica only
      Replica Reads: from any replica
      Read Repair: not relevant
      Automatic Replica Failure Detection: supported
      Automatic Failover: not supported
      Automatic New Master Election after Failure: not supported
      Replica Recovery and Resynchronization: performed by administrator
    Data Distribution:
      Data Distribution Architecture: master-single slave
      Data Distribution Method: assigned key ranges to nodes
      Automatic Data Rebalancing: [new storage triggered, data growth triggered]
      Physical Data Distribution: [single cluster, rack-aware on single cluster]
      Query Architecture: direct shard connection only (resolved in client)
      Queries using Non-Shard Key Value: non-indexed (scan)
      Merging Query Results from Multiple Shards: sorted order
    Security:
      Client Authentication: [Kerberos, SSL]
      Server authentication: shared keyfile
      Credential Store: external file
      Role Based Security: supported
      Security Role Options: [default roles, custom Roles]
      Scope of Roles: [cluster, database, collection, field]
      Database Encryption: supported
      Logging: [configurable event logging, Fixed event logging]
    Admin:
      Configuration Files: multiple
      Node command line access: non-authenticated
      Node addition/removal: single file
      Cluster monitoring: real-time
      Dump database configuration: not supported
      Database object count: not supported
      Physical storage usage: supported
